dofile("tests/spec_helper.lua")
_dofile = dofile
xr_conditions = {}
xr_effects = {}
dialogs_jupiter = {}
db = {actor={}, anomaly_by_name={}}
assert(loadfile('gamma_walo/gamedata/scripts/warfare_monkeypatches.script','t',_ENV))()

describe('warfare_monkeypatches', function()
    it('adds patched functions', function()
        assert.is_function(xr_conditions.has_task_target_anomaly)
        assert.is_function(xr_effects.setup_task_target_anomaly)
    end)
end)
