-- @ Version: SCREEN SPACE SHADERS - UPDATE 17
-- @ Description: Rain script - Settings
-- @ Author: https://www.moddb.com/members/ascii1457
-- @ Mod: https://www.moddb.com/mods/stalker-anomaly/addons/screen-space-shaders

-- If you're not using MCM you can customize your settings here --

ssfx_default_settings = 
{
	["quality"]			= 0,

	["render_scale"]	= 1.0,
	["blur"]			= 0.25,
	["use_noise"]		= 0.0,


	["general_int"]		= 1.15,
	["sky_int"]			= 1.3,
	["weapon_int"]		= 0.45,
	["weapon_int_max"]	= 0.05,

}

----------------------------------------------------