describe('WALO-2 dialogs.script update', function()
  it('adds important document rewards', function()
    local f = assert(io.open('gamma_walo/gamedata/scripts/dialogs.script', 'r'))
    local data = f:read('*all')
    f:close()
    assert.is_true(data:find('main_story_1_quest_case') ~= nil)
    assert.is_true(data:find('main_story_7_mon_con_documents') ~= nil)
  end)
end)
